### ISSUE TITLE
check if there is any stdin to get

### ISSUE THREAD

**Issue by matthewmueller** [sindresorhus/get-stdin#1]
Looks like `process.stdin.isTTY` checks to see if there is any data to get.

Otherwise, this function just hangs.

**Comment by moos** [comment]
I was surprise to find this very popular module doesn't support TTY.  This would be very useful to have for a CLI program, and is easy enough to add (i.e., by listening for ^z or ^d as EOT markers in the input).  Would you be willing to entertain a PR?

**Comment by sindresorhus** [comment]
@moos I'm not really sure what you're asking for. Can you elaborate or provide an example of what you're trying to achieve?

**Comment by moos** [comment]
I'd like to be able to run a program and have it read from the keyboard as well as a pipe.  getStdin works for:

$ echo 'abc' | foo -

but not for:

$ foo -
abc
def
^d
$

The dash in 'foo -' tells it to read STDIN (by convention only).  Hope that's clear.
