### ISSUE TITLE
Break line present at the end

### ISSUE THREAD

**Issue by Kikobeats** [sindresorhus/get-stdin#22]
I'm using `get-sdtdin` at [regexgen-cli](https://github.com/Kikobeats/regexgen-cli) and I noticed that an `\n` is always present at the final of the input:

```js
getStdin().then(stdin => {
  console.log(stdin)
  console.log([].concat(stdin))
})
```

```bash
❯ echo hola | regexgen
hola

[ 'hola\n' ]
```

**Comment by sindresorhus** [comment]
And what is the problem exactly? This module just consumes the whole stdin, the last `\n` produced by `echo` included.

**Comment by Kikobeats** [comment]
If this behavior is the expected then is ok and is my reponsability clean or not the break line 😄

**Comment by sindresorhus** [comment]
Yes, it's expected. In `execa`, I use [`strip-eof`](https://github.com/sindresorhus/strip-eof) to remove it. Might be helpful for you too.

**Comment by Kikobeats** [comment]
Thanks!
