### ISSUE TITLE
The non-promise api v4.0.1 npm package is missing a license file.

### ISSUE THREAD

**Issue by opichals** [sindresorhus/get-stdin#26]
Could you please create a new patch release of the 4.x line so that the npm cli would pick the license file?

**Comment by sindresorhus** [comment]
Sorry I don't update older major releases.

**Comment by opichals** [comment]
The issue is that the old releases are used from other packages and the fact that the license is missing in get-stdin is making it proprietary unlicensed code and the dependents therefore unusable.

As the dependents mostly use `^4.0.1` semver convention just publishing 4.0.2 would fix the situation and contribute to the greater good of the npm ecosystem itself.
