### ISSUE TITLE
Reading JSON File from stdin

### ISSUE THREAD

**Issue by malikkamranabid** [sindresorhus/get-stdin#30]
How do i read **JSON** file by using this package. I am using following command to get stdin but using this package it does-not work.
`cat airlines/british_airways/example_input.json | tsc && node dist/index.js `

**Comment by sindresorhus** [comment]
```js
const getStdin = require('get-stdin');

(async () => {
	console.log(JSON.parse(await getStdin()));
	//=> {foo: true}
})();
```

**Comment by malikkamranabid** [comment]
@sindresorhus 
`{
  "flight": {
    "segments": [
      {
        "legs": [
          {
            "departureAirport": "VIE",
            "arrivalAirport": "TXL",
            "fareFamily": "STANDARD",
            "fareClass": "Y",
            "fareBasis": "YXWHHA",
            "flightNumber": "5848",
            "departureTime": "2020-01-10T19:15",
            "arrivalTime": "2020-01-10T20:35",
            "airline": "U2"
          }
        ]
      },
      {
        "legs": [
          {
            "departureAirport": "TXL",
            "arrivalAirport": "VIE",
            "fareFamily": "STANDARD",
            "fareClass": "Y",
            "fareBasis": "YXWHHA",
            "flightNumber": "5845",
            "departureTime": "2020-01-18T13:00",
            "arrivalTime": "2020-01-18T14:20",
            "airline": "U2"
          }
        ]
      }
    ]
  },
  "passengers": [
    {
      "id": 0,
      "dateOfBirth": "1990-01-01"
    },
    {
      "id": 1,
      "dateOfBirth": "1991-01-01",
      "infantOnLap": {
        "dateOfBirth": "2019-01-01"
      }
    },
    {
      "id": 2,
      "dateOfBirth": "2019-01-01"
    }
  ]
}`

Can you try this json as a file and see does it work for you ?

**Comment by malikkamranabid** [comment]
I am using pip operator so try reading the file like this 
cat airlines/british_airways/example_input.json |  node index.js

**Comment by malikkamranabid** [comment]
Thanks
